### ISSUE TITLE
Question about cost evaluation for SWAP*

### ISSUE THREAD

**Issue by N-Wouda** [vinymax10/AILS-CVRP#1]
https://github.com/vinymax10/AILS-CVRP/blob/9b1936ce154fea22a6f3f4b3f2b0832ee2027c47/src/Evaluators/CostEvaluation.java#L88

Should this not return the calculated cost?

**Comment by vinymax10** [comment]
Hi Niels Wouda,

Thanks for the feedback. You are right. I updated the repository.

Abraços,

Vinícius R. Máximo.


Em sáb., 4 de mai. de 2024 às 06:33, Niels Wouda ***@***.***>
escreveu:

**Comment by N-Wouda** [comment]
Hi Vinícius,

Great! I noticed this while studying your implementation to see if we can use (parts of) your algorithm in PyVRP. Thanks for making this available to the community!

Best,
Niels
